# Generated by Django 5.1.6 on 2025-02-12 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('vip_price', models.DecimalField(decimal_places=2, default=150.0, max_digits=6)),
                ('standard_price', models.DecimalField(decimal_places=2, default=50.0, max_digits=6)),
                ('seats', models.JSONField(default=dict)),
            ],
        ),
    ]
