# Generated by Django 5.1.6 on 2025-02-14 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_promocode'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
