# Generated by Django 5.1.6 on 2025-02-12 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancellation_insurance',
            field=models.BooleanField(default=False),
        ),
    ]
