# Generated by Django 5.1.6 on 2025-02-12 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_promocode'),
        ('tickets', '0002_booking_cancellation_insurance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('tickets', models.JSONField()),
                ('seat_selection', models.JSONField()),
                ('promo_code', models.CharField(blank=True, max_length=20, null=True)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cancellation_insurance', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
        ),
    ]
